### ISSUE TITLE
 BUFRLIB: RDMSGW - SKIPPING CORRUPTED MESSAGE

### ISSUE THREAD

**Issue by SudhirNadiga-NOAA** [NOAA-EMC/NCEPLIBS-bufr#495] opened 2023-05-08 04:03 UTC
@ilianagenkova @jbathegit @jack-woollen  @ am seeing this error in the satellite ingest logs. Please check here:
4;m[clogin07 /lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/CRIS/ingest_logs]$ ls -l tranjb_ingest_cris_fsr_431.out
-rw-r--r-- 1 sudhir.nadiga obsproc 9930707 May  8 03:42 tranjb_ingest_cris_fsr_431.out

Running go_chkdat on the tank for that day also shows this error. This may be related on problems that the GSI
is having reading the files. Andrew is reporting this error:
/scratch1/NCEPDEV/stmp2/Andrew.Collard/ROTDIRS/v16.3.5_n21_cris/logs/2023040418/gdasanal.log.4
The error is on line 14998:
 ***********BUFR ARCHIVE LIBRARY ABORT**************
 BUFRLIB: USRTPL - REPLICATION FACTOR OVERFLOW (EXCEEDS MAXIMUM OF   255 ({GCRCHN}  )
***********BUFR ARCHIVE LIBRARY ABORT**************

We will begin investigating this error now, and we hope to find a sturdy solution. Any help from Jack and Jeff is welcome. 

Jack had emailed a temporary solution. 

-------------------------- JACK WOOLLEN TEMPORARY SOLUTION --------------------------------------
After puzzling over the corrupted message warnings, it turns out they are being generated when tranjb is reading through the tank file in order to append new data onto the end. In other words, there is pre-existing garbage in the tank files, probably left over from failed runs during testing. I notice a number of tranjb aborts among the logs. Garbage in a tank can be removed easily! The script example below shows how. If you run it twice you will see the garbage has disappeared.

Jack

set -euax
clean=/lfs/h2/emc/global/noscrub/Jack.Woollen/jwfork/build/utils/split_by_subset
tank=/lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/SCRIPTDIR/SEMIOPS/TEMPNEW/20220803/b021/xx223
rm -f NC021223; $clean $tank; mv NC021223 $tank

----------------------------------------------------------------------------------------------------------------

We can first try to see if this solves the problem for Andrew and if we can incorporate it in the satingest code. 
Any alternate solutions (e.g., increasing the default value for the problematic bufrlib variable) can also be
investigated.

**Comment by jack-woollen** [comment] 2023-05-08 13:20
I'm looking at
/lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/CRIS/ingest_logs/tranjb_ingest_cris_fsr_431.out.
Where are all the corrupted messages coming from? Presumably they are in
the tank files.
So how did they get there?

Here's a binv on one of the tanks, also counting unique lines. Notice too
many bytes to count in a 4byte integer.
Plus this tank file contains 3729 unreadable messages!

binv
/lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/CRIS/20230502/b021/xx206|uniq -c

   3729  BUFRLIB: RDMSGW - SKIPPING CORRUPTED MESSAGE
      1
      1 type        messages       subsets         bytes
      1
      1 NC021206       45876       9609866    -394914301      209.47
      1 TOTAL          45876       9609866    -394914301

Jack

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-08 13:31
It looks to me that the satingest code is having issues writing to the tank because of corrupted messages. Is this because a write job was interrupted because the wall time expired? Or, is this related to a bufrlib default value being too small?

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-08 13:34
The satingest code is the only code writing to the tank, while the dump scripts (global, rap) are the only ones reading the tank.

**Comment by jack-woollen** [comment] 2023-05-08 13:40
Sudhir

The 255 upper limit is specified in the bufr table by curly brackets {}. If
a report has more levels than that, then it needs parens ().
IE (levels) rather than {levels}. You should not get this error when
reading though, that means file corruption to begin with. I looked at
Andrew's output on hera, which was evidently reading an iasi file. I was
able to read through all the iasi files in his script without any problem.
I'll keep looking to see what that problem might be.

Jack

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-08 13:55
Thanks, Jack. Appreciate your input.

**Comment by jack-woollen** [comment] 2023-05-09 11:51
Two things. 
1) If the tranjb or satingest program is corrupting the tank we need to know why and fix it. If its timeouts or whatever. Might need to run some offline tests to see what's happening.

2) Andrew's problem is with a cris file (NC021206) and I can duplicate the error by trying to read through the file. I'll continue to look at that.

**Comment by jack-woollen** [comment] 2023-05-09 12:45
Ok, I think the error may be with the BUFR compression. @SudhirNadiga-NOAA  can you make an uncompressed file we can look at?

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 13:23
Ok, I will check the script to see how to make an uncompressed file and chat with you via the chat.
Two questions:

1) How did you figure out that it is the BUFR compression that is causing the problem? I need to learn how to diagnose errors from the tranjb logs.

2) How do we add the fix to the satingest code?

Thanks for all your help, Jack

**Comment by ilianagenkova** [comment] 2023-05-09 13:26
Debufring a few NESDIS files showed that GCRCHN was never >255, in fact it's <20.
I think the problem is in the tank generation step and it gives GSI the impression that GCRCHN > 255. Could GCRCHN be printed in a test run? I'm guessing that it might have been set to some big integer MISSING.

Also, we have never  heard of or seen this problem in operations, so...wall time limitations (at times!) might be a problem. 

Hope this is helpful info...

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 13:37
Would this be in the files in the stmp (RUNDIR)?

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 13:47
Here is the most recent RUNDIR:
/lfs/h2/emc/stmp/sudhir.nadiga/57241/jobid_satingestSMAP_npp_cris_431_1331
[clogin05 /lfs/h2/emc/stmp/sudhir.nadiga/57241/jobid_satingestSMAP_npp_cris_431_1331]$ grep -i 'GCRCHN' *                                            
[clogin05 /lfs/h2/emc/stmp/sudhir.nadiga/57241/jobid_satingestSMAP_npp_cris_431_1331]$ 

We may have to run a local version of bufr_tranjb and add print statements everywhere. What do you think?

**Comment by jack-woollen** [comment] 2023-05-09 15:04
Well, just reading through the whole compressed file with readsb eventually says GCRCHN is > 255. The rub is GCRCHN cannot possibly ever be greater than 255 because it is stored in 8 bits. Compression can smoosch things up in a way that something like that could seem to be happening. My test code just reads every subset in the compressed file, and the error occurs deep down in the middle of the file somewhere. You should be able to save a copy of the uncompressed version from somewhere in the process. Then we can try to read through that file to see if the error occurs. If it doesn't we know where the problem is.

By the way if debufr can read through the whole compressed file without hitting the problem, than maybe the error is in the readsb code tree. It would still be good to have an uncompressed version to look at.

**Comment by jack-woollen** [comment] 2023-05-09 15:09
FYI, I'm working with the file Andrew is having trouble reading on hera.

/scratch1/NCEPDEV/stmp2/Jack.Woollen/andrew/gdas.t18z.crisf4.tm00.bufr_d

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 15:16
OK, I think to save the uncompressed file, we will need to run a local version of bufr_tranjb. 
Is readsb part of the bufr_tranjb code?
If the tanks are corrupt, everything downstream (global dumps and Andrew's GSI run)  will show that error.
We will have to figure out the error at the satingest level.

**Comment by jack-woollen** [comment] 2023-05-09 15:23
I don't think tranjb compresses the data. Probably the step before that.

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 15:28
Ok, this is the code that works on CrIS files:
[clogin07 /lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/GITHUBDIR/f_sat451.COPYINGEST/sorc/bufr_tranmtypsbt.fd]$ ls -lrt
total 40
-rw-r--r-- 1 sudhir.nadiga obsproc 35891 Apr 19 17:18 tranmtypsbt.f
-rw-r--r-- 1 sudhir.nadiga obsproc   550 Apr 19 17:18 CMakeLists.txt
[clogin07 /lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/GITHUBDIR/f_sat451.COPYINGEST/sorc/bufr_tranmtypsbt.fd]$

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 15:38
I will now look inside the code.

**Comment by jack-woollen** [comment] 2023-05-09 15:49
That code just modifies the header without changing anything else. The compression is happening before this step.
I'm scanning the compressed file with ufdump to see if it generates the error. If not maybe its readsb making the error. If it does hit the error, then its probably the compression step. I wonder if NESDIS, or whoever we get it from, does the compression?

**Comment by jack-woollen** [comment] 2023-05-09 16:15
It hits the error after reading ~1.17M subsets. So there's more than a million good reports (out of 1.4M) before the error. To be honest we still don't know if its writing the compression or reading the compression causing the error. Or really if it has anything to do with compression. Having a uncompressed version would be helpful for comparison though.

**Comment by jack-woollen** [comment] 2023-05-09 19:54
@jbathegit  @ilianagenkova @SudhirNadiga-NOAA After reading the "bad" cris file a few dozen times, with various diagnostics, I'm still not sure where the error comes from, but it certainly is a problem of some sort.  Using prints and counts the (one) bad message was identified as message number 7122. So I copied that message into a file of its own. The strange part is I can read the isolated bad message just fine. But if I copy the bad message along with the 2 prior good messages, then the bad message (message #3 in the 3 message isolated file) does generate the error when trying to read it. Plus the contents of the bad message is odd. The first 2 messages in the file of 3 look normal. If anyone would care to look at the 2 isolated files they are both in /scratch1/NCEPDEV/stmp2/Jack.Woollen/andrew on hera, called badmsg.1 and badmsg.3. You can see what I see by running debufr on each one. Fyi, the full file is gdas.t18z.crisf4.tm00.bufr_d copied, from Andrew's parallel run.

This looks like a case where something corrupted a file in the tank, then a weird message survived into a dump. Why it can be read as an isolated message, but not in combination with any other messages is just part of the weirdness. I now don't think the compression is the problem. Something systematic is interfering with the ingest of this data into the tanks.  Maybe tranjb or maybe bufrlib, or maybe linux? Its kind of like being back where we started. Sorry about that!

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-09 21:17
The tranjb log shows the warning when it is attempting to write to the tank. If we write the messages to datafiles in /stmp, we can check them and see if there is anything weird.  If there is anything weird, then there is a problem with the reading of the NESDIS bufr files or with the original NESDIS bufr files. If there is nothing weird, we will need to look into where the satingest code writes to the tank. Looks like a lot of investigating in any case.

**Comment by jack-woollen** [comment] 2023-05-10 07:13
Its a good bet for me the problem is in the files before they go into the tank. If I'm not mistaken, tranjb just copies whole messages, intact, directly into a tank. This little code will test read a pre-tank file. It needs the file linked to fort.20 and the bufr table linked to fort.21.

      program readmp
      character*8 subset
      iret=isetprm('MAXSS',250000)
      call openbf(20,'IN',21)
      do while(ireadmg(20,subset,idate).eq.0)
      do while(ireadsb(20).eq.0)
      enddo
      enddo
      end program

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-10 12:06
Ok, let me try to print the data that tranjb is writing to the tank. I will get back to you.

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-11 14:40
I am going through the flow of data and scripts invoked in here:
/lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/SCRIPTDIR/SEMIOPS/OUTPUT/satingest_satingestSMAP_npp_cris_431_%idate%_1431.out
I can figure out which script is reading the files and which is writing out. I will write out the data before the script writes to the tank.

**Comment by jack-woollen** [comment] 2023-05-17 20:31
@SudhirNadiga-NOAA  It looks like a lot of the cris jobs in that directory time out.

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-18 02:51
A lot of satingest jobs time out, but this hasn't caused errors before. For example, 
[clogin01 /lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/SCRIPTDIR/SEMIOPS/OUTPUT]$ grep 'job killed: walltime' satingest_rel.v4.6.1_aerosol__0*
satingest_rel.v4.6.1_aerosol__0049.out:=>> PBS: job killed: walltime 3331 exceeded limit 3300
satingest_rel.v4.6.1_aerosol__0119.out:=>> PBS: job killed: walltime 3309 exceeded limit 3300
satingest_rel.v4.6.1_aerosol__0849.out:=>> PBS: job killed: walltime 3304 exceeded limit 3300
[clogin01 /lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/SCRIPTDIR/SEMIOPS/OUTPUT]$

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-18 02:51
I am working on writing out the contents of the data, just before the script writes to the tank, so we know if there is anything wrong with the data before the tank is written to.

**Comment by ilianagenkova** [comment] 2023-05-26 14:30
@SteveStegall-NOAA  for awareness

**Comment by edwardhartnett** [comment] 2023-05-26 15:06
I hope that this work is being captured in one or more tests for NCEPLIBS-bufr...

**Comment by ilianagenkova** [comment] 2023-05-26 16:15
Plan after today's chat (with @jack-woollen @SudhirNadiga-NOAA @SteveStegall-NOAA ):
= save NEDIS data on the fly , DATAROOT noscrub !!! SN
= get netcdf from NESDIS, share with Jack  IG
= get NESDIS Bufr toolkit link IG
= get NESDIS BUFR 04042023 IG
= use 431 fixfile for 431 data
= 2211 on 431 ? SN
= add JW code at the top of bufrtrantypsbt.fd (readmp in GitHub) SN
= make JW code into a stand alone executable IG
= check SN’ daily tanks with JW code, email if wrong IG
= work on ireadsb that would return a proper error code, or something along these lines JW

 - line 470 in bufrtranttypsbt.fd/ tran*…
 Add the code, but first define new variables
 Do… (JW code)
if…all is read…
then
do go_ahead_with_bufrtransubtyp 
else  
add_new_err_message_* exit
Endif
End do (of JW code loop)

**Comment by ilianagenkova** [comment] 2023-05-26 16:36
> I hope that this work is being captured in one or more tests for NCEPLIBS-bufr...

@edwardhartnett , we are still figuring out a solution, but will keep the big picture in mind too

**Comment by jack-woollen** [comment] 2023-05-26 20:47
@jbathegit @edwardhartnett I believe there's a workaround for this particular problem of bad cris data. The fix is in the bufrlib repo in branch jsw_cris_fix. It is on wc2 in /lfs/h2/emc/global/noscrub/Jack.Woollen/cris-fix directory. There is script "cwx" there to do a compile.

/lfs/h2/emc/global/noscrub/Jack.Woollen/cris-fix/build/path1/lib64/libbufr_4.a
/lfs/h2/emc/global/noscrub/Jack.Woollen/cris-fix/build/path1/include/bufr_4

I was able to read through the original cris trouble file from Andrew's experiment. It skipped over 20 bad subsets (1 bad message). Maybe Jeff can look over the changes I make to readsb, rdcmps, and usrtpl to see if something like this could be moved into the upcoming new release.

**Comment by jack-woollen** [comment] 2023-05-26 23:07
@ilianagenkova @SudhirNadiga-NOAA  If Andrew compiled the gsi he uses with this branch of bufrlib, he should be good to go reading the cris data..

**Comment by SudhirNadiga-NOAA** [comment] 2023-05-27 14:59
We can test this fix on satingest first. If it works for satingest, it can
be applied to the dump scripts and gsi later.

Thanks,

Sudhir

-------------------------------------------------------------------------
*Lynker* at NOAA/NWS/NCEP/EMC (ObsProc Team),
5830 University Research Court, College Park, MD 20740;
Phone: (301) 683-3751; Email: ***@***.***

**Comment by ilianagenkova** [comment] 2023-05-29 17:25
@jack-woollen , thanks for finding a solution. We will test it (on tanks) and have @ADCollard test it (on dumps) too. Not sure how the timing of implementing everything will mesh, but we will figure it our. Thanks!!!

**Comment by jbathegit** [comment] 2023-05-30 13:55
@jack-woollen thanks for this, but a few issues/questions before we try to include this in the upcoming release:

1. First off, am I understanding correctly that the underlying cause is a bad message of 20 bad data subsets from the provider (NESDIS?), and if so has any attempt been made to reach out to them to fix the problem on their end?  Are they using our library to do the encoding?  If so, then maybe the real problem is somewhere in the encoding where that replication factor gets encoded in the first place.  I also wonder how old of a version of our library they may be using, or if maybe they're just not using it correctly.  Some of these may be questions that @ilianagenkova or @SudhirNadiga-NOAA can help us track down with the data provider, but I'd really like to better understand the root problem before we just throw in a very targeted fix for a very specific issue and before we know how/why it really occurred in the first place, or whether it can be fixed on the encoding side.  In short, and if it's really a bad replication factor, then I'd really like to understand how it got there in the first place!  I'm also wondering why this particular issue would have never cropped up before, considering how many different types of compressed BUFR datasets we've processed from NESDIS going back multiple decades.
2. Secondly, Jack, in order to include this in the code baseline we're going to need a PR with an accompanying test case.  I realize you'll need me to add a testfile to the .tgz archive on emcrzdm before you can submit the PR, but before I can do that I'll need a much smaller testfile than the 1.3 Gb behemoth in your cris-fix test directory.  Is there any way you could significantly trim that down so that it only contains a few messages including the bad one?
3. And on the coding side, is there some particular reason why you introduced a new common block `common /alarms/` rather than using the existing module `moda stcode` and subroutine igetsc like we discussed last Friday?  Also, if you want to include any print output, then this should be done via subroutine errwrt rather than a direct `print *` to stdout from inside the library.

**Comment by ilianagenkova** [comment] 2023-05-31 21:40
@jack-woollen , @jbathegit 

I just tried compiling Jack's bufr branch (jsw_cris_fix), but got an error. So I tried building the /deveop branch - another error -

[ 93%] Linking Fortran executable intest8_d
[ 93%] Linking Fortran executable intest8_4
/lfs/h2/emc/obsproc/noscrub/iliana.genkova/GIT/play/NCEPLIBS-bufr/test/test_ufbrw.F90(165): error #6345: Either a PAUSE, STOP or ERROR STOP statement has an invalid argument.   [N]
          stop n  
---------------^
/lfs/h2/emc/obsproc/noscrub/iliana.genkova/GIT/play/NCEPLIBS-bufr/test/test_ufbrw.F90(167): error #6345: Either a PAUSE, STOP or ERROR STOP statement has an invalid argument.   [N]
          stop n  
---------------^
compilation aborted for /lfs/h2/emc/obsproc/noscrub/iliana.genkova/GIT/play/NCEPLIBS-bufr/test/test_ufbrw.F90 (code 1)
make[2]: *** [test/CMakeFiles/test_ufbrw_4.dir/build.make:80: test/CMakeFiles/test_ufbrw_4.dir/test_ufbrw.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2193: test/CMakeFiles/test_ufbrw_4.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Linking Fortran executable outtest9_4
[ 93%] Linking Fortran executable intest1_4
[ 93%] Built target intest3_4
[ 93%] Built target outtest4_8
[ 93%] Built target intest8_d
[ 93%] Built target intest8_4
[ 93%] Built target test_ufbcup_8
[ 93%] Built target intest1_4
[ 93%] Built target outtest9_4
make: *** [Makefile:158: all] Error 2

I am running the following in 
/lfs/h2/emc/obsproc/noscrub/iliana.genkova/GIT/play/NCEPLIBS-bufr  -

mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=./install ..
make -j8

What am I doing wrong? I had build BUFR before (on Hera).

**Comment by ilianagenkova** [comment] 2023-05-31 21:47
I just rebuild NCEPLIB-bufr on Hera fine.

What modules must be loaded on WCOSS2 for NCEPLIB-bufr  to build?

**Comment by jack-woollen** [comment] 2023-05-31 21:47
Iliana
Copy my modified code for test_ufbrw.F90 from
/lfs/h2/emc/global/noscrub/Jack.Woollen/cris-fix/NCEPLIBS-bufr/src.
Thanks
Jack

**Comment by jack-woollen** [comment] 2023-05-31 21:51
You had the libraries right. There's a bug in the test_ufbrw code that only
kicks on wcoss2. It will be fixed in develop.

**Comment by jack-woollen** [comment] 2023-05-31 21:56
Iliana
Just fixed the error in branch jsw_cris_fix branch.
Jack

**Comment by ilianagenkova** [comment] 2023-05-31 21:58
Do you meant /lfs/h2/emc/global/noscrub/Jack.Woollen/cris-fix/NCEPLIBS-bufr/**test**/test_ufbrw.f  ?

**Comment by ilianagenkova** [comment] 2023-05-31 21:58
OK, let me try with the updated branch.

**Comment by jack-woollen** [comment] 2023-05-31 22:00
Yes, that's the one.

**Comment by ilianagenkova** [comment] 2023-05-31 22:01
Great, we built and installed! :) let's try now  building satingest with your bufr branch

**Comment by ilianagenkova** [comment] 2023-05-31 22:47
I assume we need to build satingest and tranjb but pointing at Jack's bufr branch.
We followed @aerorahul 's instructions (for obsproc and prepobs) and did the following:

1) comment out the bufr load commands in /modulefiles/*_common.lua (for satingest and bufr_tranjb)
2) CMAKE_OPTS="-Dbufr_ROOT=/lfs/h2/emc/obsproc/noscrub/iliana.genkova/GIT/NCEPLIBS-bufr" ./ush/build.sh (for satingest)
3)bufr_ROOT="/lfs/h2/emc/obsproc/noscrub/iliana.genkova/GIT/play/NCEPLIBS-bufr" ./ush/build.sh

However, it looks like CMAKE_OPTS and bufr_ROOT are not valid variables, b/c we get errors - logs are:
(on Dogwood)
/lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/GITHUBDIR/rel.sat.v461.CRIS/build/CMakeFiles/CMakeOutput.log
/lfs/h2/emc/obsproc/noscrub/sudhir.nadiga/GITHUBDIR/bufr_tranjb.v1.0.3/build/CMakeFiles/CMakeOutput.log

What would be the correct build commands, Rahul? 
Thanks

**Comment by jbathegit** [comment] 2023-06-01 14:25
re: the library aspect of this, I took a deep dive on this yesterday.  I was able to whittle down Jack's original file to a much smaller size for testing, while still being able to reproduce the failure.  The message in question is the 7127th message in the original file, counting the DX table and dump center/time messages at the front of the file (or, if you exclude those, the 7120th data message).  It's 20088 bytes long, but the last 1500 bytes or so are just a repeating 40+ byte pattern of garbage fill up to the end "7777" indicator.

So the message definitely has some encoding errors, but pinpointing where things really break down is tricky, especially since (as others have noted) the behavior of the decoding software is different depending on whether the bad message is the first to be read or else is stored behind other data messages in the file.  In either case, only the first 229 replications of CRCHNM in the message (out of 431 total) contain any actual data, and everything behind that is into the garbage fill.

Furthermore, in either case, the bad content beyond the 229th replication of CRCHNM causes it to read a bad value for {GCRCHN} which points it to beyond the end of the message, where it's reading whatever happens to be stored in those bytes of the internal MBAY array that holds the message.  So when the bad message is the first one in the file to be read, those bytes beyond the end of the message are still initialized out to zero and it reads a value of 0 for {GCRCHN}, which allows it to read through the message without aborting even though much of the output is still garbage.  But in the second case, the bytes in MBAY beyond the end of the message contain whatever was left over there from the much longer previous message that was in front of it in the file.  In that case, it reads a value of 396 for {GCRCHN}, which in turn causes the abort since it's a number bigger than 255.

In any case, I agree the solution is to add a patch to the library to trap any such bad replication counter and just have readsb return a value of -1 to skip past the entire message.  Thanks to Jack for providing a prototype on how to do this, and I'll take that logic and incorporate it into the library using the existing stcode module and remove the extra print statements.  I'll also upload the bad message as a new test case for the CI testing suite, and then I'll get all of this packaged up with the new 12.0.0 release and get it tagged and out the door as soon as possible.

Thanks also to Iliana and others who reached out to NESDIS to confirm that they were using our library and which version they were using.  I don't think the older version they were using is necessarily to blame for the generation of the bad message in the first place.  We'll have to wait and see once they upgrade to a newer version, but I suspect the real issue could be the way they're calling the various library routines to encode the messages.  My suspicion is mostly based on the fact that their "good" messages contain a {GCRCHN} value of 12, even though all of that data is "missing" and they themselves have noted that those values should all be showing up as 0.   Again, just a hunch at this point.

**Closed as completed** 2023-06-03 02:00 UTC
